// Header..: GPIOB.H
// Version.: 1.0
// Compiler: GCC-ARM
// Chip....: STM32F10x
// Date....: January 2025
// Author..: Udo Juerss
//-----------------------------------------------------------------------------

#pragma once
//-----------------------------------------------------------------------------

#include "stm32f1_gpio_common.h"
//-----------------------------------------------------------------------------

// GPIOB analog inputs
#define GPIOB_0_IN_AN() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_AN_0;}
#define GPIOB_1_IN_AN() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_AN_1;}
#define GPIOB_2_IN_AN() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_AN_2;}
#define GPIOB_3_IN_AN() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_AN_3;}
#define GPIOB_4_IN_AN() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_AN_4;}
#define GPIOB_5_IN_AN() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_AN_5;}
#define GPIOB_6_IN_AN() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_AN_6;}
#define GPIOB_7_IN_AN() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_AN_7;}
#define GPIOB_8_IN_AN() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_AN_0;}
#define GPIOB_9_IN_AN() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_AN_1;}
#define GPIOB_10_IN_AN() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_AN_2;}
#define GPIOB_11_IN_AN() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_AN_3;}
#define GPIOB_12_IN_AN() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_AN_4;}
#define GPIOB_13_IN_AN() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_AN_5;}
#define GPIOB_14_IN_AN() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_AN_6;}
#define GPIOB_15_IN_AN() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_AN_7;}

// GPIOB floating inputs
#define GPIOB_0_IN_FLT() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_FLT_0;}
#define GPIOB_1_IN_FLT() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_FLT_1;}
#define GPIOB_2_IN_FLT() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_FLT_2;}
#define GPIOB_3_IN_FLT() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_FLT_3;}
#define GPIOB_4_IN_FLT() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_FLT_4;}
#define GPIOB_5_IN_FLT() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_FLT_5;}
#define GPIOB_6_IN_FLT() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_FLT_6;}
#define GPIOB_7_IN_FLT() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_FLT_7;}
#define GPIOB_8_IN_FLT() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_FLT_0;}
#define GPIOB_9_IN_FLT() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_FLT_1;}
#define GPIOB_10_IN_FLT() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_FLT_2;}
#define GPIOB_11_IN_FLT() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_FLT_3;}
#define GPIOB_12_IN_FLT() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_FLT_4;}
#define GPIOB_13_IN_FLT() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_FLT_5;}
#define GPIOB_14_IN_FLT() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_FLT_6;}
#define GPIOB_15_IN_FLT() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_FLT_7;}

// GPIOB inputs with pullup enabled
#define GPIOB_0_IN_PU() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_PUD_0; GPIOB_0_SET();}
#define GPIOB_1_IN_PU() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_PUD_1; GPIOB_1_SET();}
#define GPIOB_2_IN_PU() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_PUD_2; GPIOB_2_SET();}
#define GPIOB_3_IN_PU() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_PUD_3; GPIOB_3_SET();}
#define GPIOB_4_IN_PU() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_PUD_4; GPIOB_4_SET();}
#define GPIOB_5_IN_PU() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_PUD_5; GPIOB_5_SET();}
#define GPIOB_6_IN_PU() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_PUD_6; GPIOB_6_SET();}
#define GPIOB_7_IN_PU() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_PUD_7; GPIOB_7_SET();}
#define GPIOB_8_IN_PU() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_PUD_0; GPIOB_8_SET();}
#define GPIOB_9_IN_PU() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_PUD_1; GPIOB_9_SET();}
#define GPIOB_10_IN_PU() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_PUD_2; GPIOB_10_SET();}
#define GPIOB_11_IN_PU() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_PUD_3; GPIOB_11_SET();}
#define GPIOB_12_IN_PU() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_PUD_4; GPIOB_12_SET();}
#define GPIOB_13_IN_PU() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_PUD_5; GPIOB_13_SET();}
#define GPIOB_14_IN_PU() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_PUD_6; GPIOB_14_SET();}
#define GPIOB_15_IN_PU() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_PUD_7; GPIOB_15_SET();}

// GPIOB inputs with pulldown enabled
#define GPIOB_0_IN_PD() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_PUD_0; GPIOB_0_CLR();}
#define GPIOB_1_IN_PD() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_PUD_1; GPIOB_1_CLR();}
#define GPIOB_2_IN_PD() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_PUD_2; GPIOB_2_CLR();}
#define GPIOB_3_IN_PD() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_PUD_3; GPIOB_3_CLR();}
#define GPIOB_4_IN_PD() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_PUD_4; GPIOB_4_CLR();}
#define GPIOB_5_IN_PD() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_PUD_5; GPIOB_5_CLR();}
#define GPIOB_6_IN_PD() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_PUD_6; GPIOB_6_CLR();}
#define GPIOB_7_IN_PD() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_PUD_7; GPIOB_7_CLR();}
#define GPIOB_8_IN_PD() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_PUD_0; GPIOB_8_CLR();}
#define GPIOB_9_IN_PD() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_PUD_1; GPIOB_9_CLR();}
#define GPIOB_10_IN_PD() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_PUD_2; GPIOB_10_CLR();}
#define GPIOB_11_IN_PD() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_PUD_3; GPIOB_11_CLR();}
#define GPIOB_12_IN_PD() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_PUD_4; GPIOB_12_CLR();}
#define GPIOB_13_IN_PD() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_PUD_5; GPIOB_13_CLR();}
#define GPIOB_14_IN_PD() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_PUD_6; GPIOB_14_CLR();}
#define GPIOB_15_IN_PD() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_PUD_7; GPIOB_15_CLR();}

// GPIOB push/pull outputs 2M/10M/50M
#define GPIOB_0_OUT_PP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_PP_0_2M;}
#define GPIOB_0_OUT_PP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_PP_0_10M;}
#define GPIOB_0_OUT_PP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_PP_0_50M;}

#define GPIOB_1_OUT_PP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_PP_1_2M;}
#define GPIOB_1_OUT_PP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_PP_1_10M;}
#define GPIOB_1_OUT_PP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_PP_1_50M;}

#define GPIOB_2_OUT_PP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_PP_2_2M;}
#define GPIOB_2_OUT_PP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_PP_2_10M;}
#define GPIOB_2_OUT_PP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_PP_2_50M;}

#define GPIOB_3_OUT_PP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_PP_3_2M;}
#define GPIOB_3_OUT_PP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_PP_3_10M;}
#define GPIOB_3_OUT_PP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_PP_3_50M;}

#define GPIOB_4_OUT_PP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_PP_4_2M;}
#define GPIOB_4_OUT_PP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_PP_4_10M;}
#define GPIOB_4_OUT_PP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_PP_4_50M;}

#define GPIOB_5_OUT_PP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_PP_5_2M;}
#define GPIOB_5_OUT_PP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_PP_5_10M;}
#define GPIOB_5_OUT_PP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_PP_5_50M;}

#define GPIOB_6_OUT_PP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_PP_6_2M;}
#define GPIOB_6_OUT_PP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_PP_6_10M;}
#define GPIOB_6_OUT_PP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_PP_6_50M;}

#define GPIOB_7_OUT_PP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_PP_7_2M;}
#define GPIOB_7_OUT_PP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_PP_7_10M;}
#define GPIOB_7_OUT_PP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_PP_7_50M;}

#define GPIOB_8_OUT_PP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_PP_0_2M;}
#define GPIOB_8_OUT_PP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_PP_0_10M;}
#define GPIOB_8_OUT_PP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_PP_0_50M;}

#define GPIOB_9_OUT_PP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_PP_1_2M;}
#define GPIOB_9_OUT_PP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_PP_1_10M;}
#define GPIOB_9_OUT_PP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_PP_1_50M;}

#define GPIOB_10_OUT_PP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_PP_2_2M;}
#define GPIOB_10_OUT_PP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_PP_2_10M;}
#define GPIOB_10_OUT_PP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_PP_2_50M;}

#define GPIOB_11_OUT_PP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_PP_3_2M;}
#define GPIOB_11_OUT_PP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_PP_3_10M;}
#define GPIOB_11_OUT_PP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_PP_3_50M;}

#define GPIOB_12_OUT_PP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_PP_4_2M;}
#define GPIOB_12_OUT_PP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_PP_4_10M;}
#define GPIOB_12_OUT_PP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_PP_4_50M;}

#define GPIOB_13_OUT_PP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_PP_5_2M;}
#define GPIOB_13_OUT_PP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_PP_5_10M;}
#define GPIOB_13_OUT_PP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_PP_5_50M;}

#define GPIOB_14_OUT_PP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_PP_6_2M;}
#define GPIOB_14_OUT_PP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_PP_6_10M;}
#define GPIOB_14_OUT_PP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_PP_6_50M;}

#define GPIOB_15_OUT_PP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_PP_7_2M;}
#define GPIOB_15_OUT_PP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_PP_7_10M;}
#define GPIOB_15_OUT_PP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_PP_7_50M;}

// GPIOB open drain outputs 2M/10M/50M
#define GPIOB_0_OUT_OD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_OD_0_2M;}
#define GPIOB_0_OUT_OD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_OD_0_10M;}
#define GPIOB_0_OUT_OD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_OD_0_50M;}

#define GPIOB_1_OUT_OD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_OD_1_2M;}
#define GPIOB_1_OUT_OD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_OD_1_10M;}
#define GPIOB_1_OUT_OD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_OD_1_50M;}

#define GPIOB_2_OUT_OD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_OD_2_2M;}
#define GPIOB_2_OUT_OD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_OD_2_10M;}
#define GPIOB_2_OUT_OD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_OD_2_50M;}

#define GPIOB_3_OUT_OD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_OD_3_2M;}
#define GPIOB_3_OUT_OD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_OD_3_10M;}
#define GPIOB_3_OUT_OD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_OD_3_50M;}

#define GPIOB_4_OUT_OD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_OD_4_2M;}
#define GPIOB_4_OUT_OD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_OD_4_10M;}
#define GPIOB_4_OUT_OD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_OD_4_50M;}

#define GPIOB_5_OUT_OD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_OD_5_2M;}
#define GPIOB_5_OUT_OD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_OD_5_10M;}
#define GPIOB_5_OUT_OD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_OD_5_50M;}

#define GPIOB_6_OUT_OD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_OD_6_2M;}
#define GPIOB_6_OUT_OD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_OD_6_10M;}
#define GPIOB_6_OUT_OD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_OD_6_50M;}

#define GPIOB_7_OUT_OD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_OD_7_2M;}
#define GPIOB_7_OUT_OD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_OD_7_10M;}
#define GPIOB_7_OUT_OD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_OD_7_50M;}

#define GPIOB_8_OUT_OD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_OD_0_2M;}
#define GPIOB_8_OUT_OD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_OD_0_10M;}
#define GPIOB_8_OUT_OD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_OD_0_50M;}

#define GPIOB_9_OUT_OD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_OD_1_2M;}
#define GPIOB_9_OUT_OD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_OD_1_10M;}
#define GPIOB_9_OUT_OD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_OD_1_50M;}

#define GPIOB_10_OUT_OD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_OD_2_2M;}
#define GPIOB_10_OUT_OD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_OD_2_10M;}
#define GPIOB_10_OUT_OD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_OD_2_50M;}

#define GPIOB_11_OUT_OD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_OD_3_2M;}
#define GPIOB_11_OUT_OD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_OD_3_10M;}
#define GPIOB_11_OUT_OD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_OD_3_50M;}

#define GPIOB_12_OUT_OD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_OD_4_2M;}
#define GPIOB_12_OUT_OD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_OD_4_10M;}
#define GPIOB_12_OUT_OD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_OD_4_50M;}

#define GPIOB_13_OUT_OD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_OD_5_2M;}
#define GPIOB_13_OUT_OD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_OD_5_10M;}
#define GPIOB_13_OUT_OD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_OD_5_50M;}

#define GPIOB_14_OUT_OD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_OD_6_2M;}
#define GPIOB_14_OUT_OD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_OD_6_10M;}
#define GPIOB_14_OUT_OD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_OD_6_50M;}

#define GPIOB_15_OUT_OD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_OD_7_2M;}
#define GPIOB_15_OUT_OD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_OD_7_10M;}
#define GPIOB_15_OUT_OD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_OD_7_50M;}

// GPIOB alternate function push/pull outputs 2M/10M/50M
#define GPIOB_0_OUT_AFPP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_AFPP_0_2M;}
#define GPIOB_0_OUT_AFPP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_AFPP_0_10M;}
#define GPIOB_0_OUT_AFPP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_AFPP_0_50M;}

#define GPIOB_1_OUT_AFPP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_AFPP_1_2M;}
#define GPIOB_1_OUT_AFPP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_AFPP_1_10M;}
#define GPIOB_1_OUT_AFPP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_AFPP_1_50M;}

#define GPIOB_2_OUT_AFPP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_AFPP_2_2M;}
#define GPIOB_2_OUT_AFPP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_AFPP_2_10M;}
#define GPIOB_2_OUT_AFPP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_AFPP_2_50M;}

#define GPIOB_3_OUT_AFPP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_AFPP_3_2M;}
#define GPIOB_3_OUT_AFPP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_AFPP_3_10M;}
#define GPIOB_3_OUT_AFPP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_AFPP_3_50M;}

#define GPIOB_4_OUT_AFPP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_AFPP_4_2M;}
#define GPIOB_4_OUT_AFPP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_AFPP_4_10M;}
#define GPIOB_4_OUT_AFPP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_AFPP_4_50M;}

#define GPIOB_5_OUT_AFPP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_AFPP_5_2M;}
#define GPIOB_5_OUT_AFPP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_AFPP_5_10M;}
#define GPIOB_5_OUT_AFPP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_AFPP_5_50M;}

#define GPIOB_6_OUT_AFPP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_AFPP_6_2M;}
#define GPIOB_6_OUT_AFPP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_AFPP_6_10M;}
#define GPIOB_6_OUT_AFPP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_AFPP_6_50M;}

#define GPIOB_7_OUT_AFPP_2M() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_AFPP_7_2M;}
#define GPIOB_7_OUT_AFPP_10M() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_AFPP_7_10M;}
#define GPIOB_7_OUT_AFPP_50M() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_AFPP_7_50M;}

#define GPIOB_8_OUT_AFPP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_AFPP_0_2M;}
#define GPIOB_8_OUT_AFPP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_AFPP_0_10M;}
#define GPIOB_8_OUT_AFPP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_AFPP_0_50M;}

#define GPIOB_9_OUT_AFPP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_AFPP_1_2M;}
#define GPIOB_9_OUT_AFPP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_AFPP_1_10M;}
#define GPIOB_9_OUT_AFPP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_AFPP_1_50M;}

#define GPIOB_10_OUT_AFPP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_AFPP_2_2M;}
#define GPIOB_10_OUT_AFPP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_AFPP_2_10M;}
#define GPIOB_10_OUT_AFPP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_AFPP_2_50M;}

#define GPIOB_11_OUT_AFPP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_AFPP_3_2M;}
#define GPIOB_11_OUT_AFPP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_AFPP_3_10M;}
#define GPIOB_11_OUT_AFPP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_AFPP_3_50M;}

#define GPIOB_12_OUT_AFPP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_AFPP_4_2M;}
#define GPIOB_12_OUT_AFPP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_AFPP_4_10M;}
#define GPIOB_12_OUT_AFPP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_AFPP_4_50M;}

#define GPIOB_13_OUT_AFPP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_AFPP_5_2M;}
#define GPIOB_13_OUT_AFPP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_AFPP_5_10M;}
#define GPIOB_13_OUT_AFPP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_AFPP_5_50M;}

#define GPIOB_14_OUT_AFPP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_AFPP_6_2M;}
#define GPIOB_14_OUT_AFPP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_AFPP_6_10M;}
#define GPIOB_14_OUT_AFPP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_AFPP_6_50M;}

#define GPIOB_15_OUT_AFPP_2M() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_AFPP_7_2M;}
#define GPIOB_15_OUT_AFPP_10M() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_AFPP_7_10M;}
#define GPIOB_15_OUT_AFPP_50M() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_AFPP_7_50M;}

// GPIOB alternate function open drain outputs 2M/10M/50M
#define GPIOB_0_OUT_AFOD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_AFOD_0_2M;}
#define GPIOB_0_OUT_AFOD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_AFOD_0_10M;}
#define GPIOB_0_OUT_AFOD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_0; GPIOB->CRL |= GPIO_MSK_AFOD_0_50M;}

#define GPIOB_1_OUT_AFOD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_AFOD_1_2M;}
#define GPIOB_1_OUT_AFOD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_AFOD_1_10M;}
#define GPIOB_1_OUT_AFOD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_1; GPIOB->CRL |= GPIO_MSK_AFOD_1_50M;}

#define GPIOB_2_OUT_AFOD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_AFOD_2_2M;}
#define GPIOB_2_OUT_AFOD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_AFOD_2_10M;}
#define GPIOB_2_OUT_AFOD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_2; GPIOB->CRL |= GPIO_MSK_AFOD_2_50M;}

#define GPIOB_3_OUT_AFOD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_AFOD_3_2M;}
#define GPIOB_3_OUT_AFOD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_AFOD_3_10M;}
#define GPIOB_3_OUT_AFOD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_3; GPIOB->CRL |= GPIO_MSK_AFOD_3_50M;}

#define GPIOB_4_OUT_AFOD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_AFOD_4_2M;}
#define GPIOB_4_OUT_AFOD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_AFOD_4_10M;}
#define GPIOB_4_OUT_AFOD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_4; GPIOB->CRL |= GPIO_MSK_AFOD_4_50M;}

#define GPIOB_5_OUT_AFOD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_AFOD_5_2M;}
#define GPIOB_5_OUT_AFOD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_AFOD_5_10M;}
#define GPIOB_5_OUT_AFOD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_5; GPIOB->CRL |= GPIO_MSK_AFOD_5_50M;}

#define GPIOB_6_OUT_AFOD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_AFOD_6_2M;}
#define GPIOB_6_OUT_AFOD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_AFOD_6_10M;}
#define GPIOB_6_OUT_AFOD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_6; GPIOB->CRL |= GPIO_MSK_AFOD_6_50M;}

#define GPIOB_7_OUT_AFOD_2M() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_AFOD_7_2M;}
#define GPIOB_7_OUT_AFOD_10M() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_AFOD_7_10M;}
#define GPIOB_7_OUT_AFOD_50M() {GPIOB->CRL &= GPIO_MSK_CLR_7; GPIOB->CRL |= GPIO_MSK_AFOD_7_50M;}

#define GPIOB_8_OUT_AFOD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_AFOD_0_2M;}
#define GPIOB_8_OUT_AFOD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_AFOD_0_10M;}
#define GPIOB_8_OUT_AFOD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_0; GPIOB->CRH |= GPIO_MSK_AFOD_0_50M;}

#define GPIOB_9_OUT_AFOD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_AFOD_1_2M;}
#define GPIOB_9_OUT_AFOD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_AFOD_1_10M;}
#define GPIOB_9_OUT_AFOD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_1; GPIOB->CRH |= GPIO_MSK_AFOD_1_50M;}

#define GPIOB_10_OUT_AFOD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_AFOD_2_2M;}
#define GPIOB_10_OUT_AFOD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_AFOD_2_10M;}
#define GPIOB_10_OUT_AFOD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_2; GPIOB->CRH |= GPIO_MSK_AFOD_2_50M;}

#define GPIOB_11_OUT_AFOD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_AFOD_3_2M;}
#define GPIOB_11_OUT_AFOD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_AFOD_3_10M;}
#define GPIOB_11_OUT_AFOD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_3; GPIOB->CRH |= GPIO_MSK_AFOD_3_50M;}

#define GPIOB_12_OUT_AFOD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_AFOD_4_2M;}
#define GPIOB_12_OUT_AFOD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_AFOD_4_10M;}
#define GPIOB_12_OUT_AFOD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_4; GPIOB->CRH |= GPIO_MSK_AFOD_4_50M;}

#define GPIOB_13_OUT_AFOD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_AFOD_5_2M;}
#define GPIOB_13_OUT_AFOD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_AFOD_5_10M;}
#define GPIOB_13_OUT_AFOD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_5; GPIOB->CRH |= GPIO_MSK_AFOD_5_50M;}

#define GPIOB_14_OUT_AFOD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_AFOD_6_2M;}
#define GPIOB_14_OUT_AFOD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_AFOD_6_10M;}
#define GPIOB_14_OUT_AFOD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_6; GPIOB->CRH |= GPIO_MSK_AFOD_6_50M;}

#define GPIOB_15_OUT_AFOD_2M() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_AFOD_7_2M;}
#define GPIOB_15_OUT_AFOD_10M() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_AFOD_7_10M;}
#define GPIOB_15_OUT_AFOD_50M() {GPIOB->CRH &= GPIO_MSK_CLR_7; GPIOB->CRH |= GPIO_MSK_AFOD_7_50M;}
//-----------------------------------------------------------------------------

// GPIOB SET/CLR/CHG/TGL/Get macros
#define GPIOB_0_SET() (GPIOB->BSRR = BIT0)
#define GPIOB_0_CLR() (GPIOB->BRR = BIT0)
#define GPIOB_0_CHG(b) {if (b) GPIOB_0_SET(); else GPIOB_0_CLR();}
#define GPIOB_0_TGL() (GPIOB->ODR ^= BIT0)
#define GPIOB_0_GET() ((GPIOB->IDR & BIT0) == BIT0)

#define GPIOB_1_SET() (GPIOB->BSRR = BIT1)
#define GPIOB_1_CLR() (GPIOB->BRR = BIT1)
#define GPIOB_1_CHG(b) {if (b) GPIOB_1_SET(); else GPIOB_1_CLR();}
#define GPIOB_1_TGL() (GPIOB->ODR ^= BIT1)
#define GPIOB_1_GET() ((GPIOB->IDR & BIT1) == BIT1)

#define GPIOB_2_SET() (GPIOB->BSRR = BIT2)
#define GPIOB_2_CLR() (GPIOB->BRR = BIT2)
#define GPIOB_2_CHG(b) {if (b) GPIOB_2_SET(); else GPIOB_2_CLR();}
#define GPIOB_2_TGL() (GPIOB->ODR ^= BIT2)
#define GPIOB_2_GET() ((GPIOB->IDR & BIT2) == BIT2)

#define GPIOB_3_SET() (GPIOB->BSRR = BIT3)
#define GPIOB_3_CLR() (GPIOB->BRR = BIT3)
#define GPIOB_3_CHG(b) {if (b) GPIOB_3_SET(); else GPIOB_3_CLR();}
#define GPIOB_3_TGL() (GPIOB->ODR ^= BIT3)
#define GPIOB_3_GET() ((GPIOB->IDR & BIT3) == BIT3)

#define GPIOB_4_SET() (GPIOB->BSRR = BIT4)
#define GPIOB_4_CLR() (GPIOB->BRR = BIT4)
#define GPIOB_4_CHG(b) {if (b) GPIOB_4_SET(); else GPIOB_4_CLR();}
#define GPIOB_4_TGL() (GPIOB->ODR ^= BIT4)
#define GPIOB_4_GET() ((GPIOB->IDR & BIT4) == BIT4)

#define GPIOB_5_SET() (GPIOB->BSRR = BIT5)
#define GPIOB_5_CLR() (GPIOB->BRR = BIT5)
#define GPIOB_5_CHG(b) {if (b) GPIOB_5_SET(); else GPIOB_5_CLR();}
#define GPIOB_5_TGL() (GPIOB->ODR ^= BIT5)
#define GPIOB_5_GET() ((GPIOB->IDR & BIT5) == BIT5)

#define GPIOB_6_SET() (GPIOB->BSRR = BIT6)
#define GPIOB_6_CLR() (GPIOB->BRR = BIT6)
#define GPIOB_6_CHG(b) {if (b) GPIOB_6_SET(); else GPIOB_6_CLR();}
#define GPIOB_6_TGL() (GPIOB->ODR ^= BIT6)
#define GPIOB_6_GET() ((GPIOB->IDR & BIT6) == BIT6)

#define GPIOB_7_SET() (GPIOB->BSRR = BIT7)
#define GPIOB_7_CLR() (GPIOB->BRR = BIT7)
#define GPIOB_7_CHG(b) {if (b) GPIOB_7_SET(); else GPIOB_7_CLR();}
#define GPIOB_7_TGL() (GPIOB->ODR ^= BIT7)
#define GPIOB_7_GET() ((GPIOB->IDR & BIT7) == BIT7)

#define GPIOB_8_SET() (GPIOB->BSRR = BIT8)
#define GPIOB_8_CLR() (GPIOB->BRR = BIT8)
#define GPIOB_8_CHG(b) {if (b) GPIOB_8_SET(); else GPIOB_8_CLR();}
#define GPIOB_8_TGL() (GPIOB->ODR ^= BIT8)
#define GPIOB_8_GET() ((GPIOB->IDR & BIT8) == BIT8)

#define GPIOB_9_SET() (GPIOB->BSRR = BIT9)
#define GPIOB_9_CLR() (GPIOB->BRR = BIT9)
#define GPIOB_9_CHG(b) {if (b) GPIOB_9_SET(); else GPIOB_9_CLR();}
#define GPIOB_9_TGL() (GPIOB->ODR ^= BIT9)
#define GPIOB_9_GET() ((GPIOB->IDR & BIT9) == BIT9)

#define GPIOB_10_SET() (GPIOB->BSRR = BIT10)
#define GPIOB_10_CLR() (GPIOB->BRR = BIT10)
#define GPIOB_10_CHG(b) {if (b) GPIOB_10_SET(); else GPIOB_10_CLR();}
#define GPIOB_10_TGL() (GPIOB->ODR ^= BIT10)
#define GPIOB_10_GET() ((GPIOB->IDR & BIT10) == BIT10)

#define GPIOB_11_SET() (GPIOB->BSRR = BIT11)
#define GPIOB_11_CLR() (GPIOB->BRR = BIT11)
#define GPIOB_11_CHG(b) {if (b) GPIOB_11_SET(); else GPIOB_11_CLR();}
#define GPIOB_11_TGL() (GPIOB->ODR ^= BIT11)
#define GPIOB_11_GET() ((GPIOB->IDR & BIT11) == BIT11)

#define GPIOB_12_SET() (GPIOB->BSRR = BIT12)
#define GPIOB_12_CLR() (GPIOB->BRR = BIT12)
#define GPIOB_12_CHG(b) {if (b) GPIOB_12_SET(); else GPIOB_12_CLR();}
#define GPIOB_12_TGL() (GPIOB->ODR ^= BIT12)
#define GPIOB_12_GET() ((GPIOB->IDR & BIT12) == BIT12)

#define GPIOB_13_SET() (GPIOB->BSRR = BIT13)
#define GPIOB_13_CLR() (GPIOB->BRR = BIT13)
#define GPIOB_13_CHG(b) {if (b) GPIOB_13_SET(); else GPIOB_13_CLR();}
#define GPIOB_13_TGL() (GPIOB->ODR ^= BIT13)
#define GPIOB_13_GET() ((GPIOB->IDR & BIT13) == BIT13)

#define GPIOB_14_SET() (GPIOB->BSRR = BIT14)
#define GPIOB_14_CLR() (GPIOB->BRR = BIT14)
#define GPIOB_14_CHG(b) {if (b) GPIOB_14_SET(); else GPIOB_14_CLR();}
#define GPIOB_14_TGL() (GPIOB->ODR ^= BIT14)
#define GPIOB_14_GET() ((GPIOB->IDR & BIT14) == BIT14)

#define GPIOB_15_SET() (GPIOB->BSRR = BIT15)
#define GPIOB_15_CLR() (GPIOB->BRR = BIT15)
#define GPIOB_15_CHG(b) {if (b) GPIOB_15_SET(); else GPIOB_15_CLR();}
#define GPIOB_15_TGL() (GPIOB->ODR ^= BIT15)
#define GPIOB_15_GET() ((GPIOB->IDR & BIT15) == BIT15)
